language: php
php:
  - 7.0
  - 7.1
before_install:
  - nvm install stable
  - npm update -g npm
  - phpenv config-rm xdebug.ini
install:
  # Composer
  - composer self-update
  - composer create-project bluzphp/skeleton --stability=dev
  - cd skeleton
  # Require current module
  - composer require bluzphp/module-test:dev-$TRAVIS_BRANCH
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
  # Migrations
  - vendor/bin/phinx migrate -e default
  - vendor/bin/phinx seed:run
before_script:
  # Newman
  - npm install -g newman
script:
  # Check code style
  - php vendor/bin/phpcs ./application --standard=PSR1,PSR2 --encoding=utf-8 --ignore=./application/_loader.php
  # Run built-in web-server
  - php vendor/bin/bluzman server:start --host 127.0.0.1 -b
  # Run CodeCeption tests
  - php vendor/bin/bluzman test module-categories
  # Run postman/newman tests
  - newman run tests/postman/test/collection.json -e tests/postman/test/environment.json
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
branches:
  only:
  - master
  - develop
