language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - master
matrix:
  allow_failures:
    - php: master
env:
  - BLUZ_MODULE=test
before_install:
  - nvm install stable
  - npm update -g npm
  - phpenv config-rm xdebug.ini
install:
  # Newman
  - npm install -g newman
  # Composer
  - composer self-update
  - composer create-project bluzphp/skeleton --stability=dev
  # Require current module
  - cd skeleton
  - composer require bluzphp/module-$BLUZ_MODULE:dev-$TRAVIS_BRANCH
before_script:
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
  # Migrations
  - php vendor/bin/bluzman db:migrate
  - php vendor/bin/bluzman db:seed:run
script:
  # Check code style
  - php vendor/bin/phpcs ./application --standard=PSR1,PSR2 --encoding=utf-8 --ignore=./application/_loader.php
  # Run built-in web-server
  - php vendor/bin/bluzman server:start --host 127.0.0.1 -b -e testing
  # Run CodeCeption tests
  - php vendor/bin/bluzman test module-$BLUZ_MODULE
  # Run postman/newman tests
  - newman run tests/postman/$BLUZ_MODULE/collection.json -e tests/postman/$BLUZ_MODULE/environment.json
notifications:
  email: false
branches:
  only:
  - master
  - develop
