<a href="<?= $this->url('test', 'create') ?>" class="btn btn-primary">Create New</a>

<dl>
    <?php foreach ($row->toArray() as $key => $value) : ?>
      <dt><?= $key ?></dt>
      <dd><?= $value ?></dd>
    <?php endforeach; ?>
</dl>

<a href="<?= $this->url('test', 'update', ['id' => $row->id]) ?>" class="btn"
   data-aajax-dialog data-ajax-method="GET">Edit</a>
<a href="<?= $this->url('test', 'delete', ['id' => $row->id]) ?>" class="btn btn-danger"
   data-confirm data-ajax data-ajax-method="DELETE">Delete</a>
