<?php $uid = uniqid('form_', false); ?>
<form id="<?= $uid ?>" action="<?= $this->url('test', 'crud') ?>" class="form-horizontal"
      data-ajax method="<?= $method ?>">
  <input type="hidden" name="id" value="<?= $row->id ?>"/>
  <div class="modal-header">
    <h4 class="modal-title">Test Table</h4>
    <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
  </div>
  <div class="modal-body">
    <div class="form-group">
      <label class="col-form-label col-lg-2" for="name"><?= __('Name') ?></label>
      <div class="col-lg-10">
        <input type="text" class="form-control" id="name" name="name" value="<?= ($row->name) ?>" required/>
      </div>
    </div>
    <div class="form-group">
      <label class="col-form-label col-lg-2" for="email"><?= __('Email') ?></label>
      <div class="col-lg-10">
        <input type="email" class="form-control" id="email" name="email" value="<?= ($row->email) ?>" required/>
      </div>
    </div>
    <div class="form-group">
      <label class="col-form-label col-lg-2" for="status"><?= __('Status') ?></label>
      <div class="col-lg-10">
        <select id="status" name="status" class="form-control">
          <option <?= $row->status === 'active' ? 'selected' : '' ?>>active</option>
          <option <?= $row->status === 'disable' ? 'selected' : '' ?>>disable</option>
          <option <?= $row->status === 'delete' ? 'selected' : '' ?>>delete</option>
        </select>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
    <button type="button" class="btn btn-light" data-bs-dismiss="modal"><?= __('Close') ?></button>
  </div>
</form>

<?php
// need for plain request
if (isset($errors)) :
    $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>
