<?php

use Application\Test;
use Bluz\Proxy\Db;

require_once __DIR__ .'/partial/demo.phtml';
?>
<h2>Example of usage Db Query Builders</h2>
<p class="lead">Please, never use <code>Db</code> or <code>Query</code> inside <code>View</code></p>
<hr/>


<section class="mt-4">
  <h3>Select</h3>
  <hr/>
  <pre class="alert alert-secondary"><code>$selectBuilder = Db::select('u.*', 'ua.*')
    ->from('users', 'u')
    ->leftJoin('u', 'users_actions', 'ua', 'ua.userId = u.id')
    ->where('u.id = ? OR u.id = ?', 4, 5)
    ->orWhere('u.id IN (?)', [4, 5])
    ->andWhere('u.status = ? OR u.status = ?', 'active', 'pending')
    ->orWhere('u.login LIKE (?)', 'A%')
    ->orderBy('u.id')
    ->addOrderBy('u.login')
    ->limit(5);</code></pre>
  <div>
  <?php
      $selectBuilder = Db::select('u.*', 'ua.*')
          ->from('users', 'u')
          ->leftJoin('u', 'users_actions', 'ua', 'ua.userId = u.id')
          ->where('u.id = ? OR u.id = ?', 4, 5)
          ->orWhere('u.id IN (?)', [4, 5])
          ->andWhere('u.status = ? OR u.status = ?', 'active', 'pending')
          ->orWhere('u.login LIKE (?)', 'A%')
          ->orderBy('u.id')
          ->addOrderBy('u.login')
          ->limit(5);
      demo($selectBuilder->getQuery());
  ?>
</section>

<section class="mt-4">
  <h3>Insert</h3>
  <hr/>
  <pre class="alert alert-secondary"><code>$insertBuilder = Db::insert('users')
    ->set('login', 'example')
    ->set('email', 'example@domain.com');</code></pre>
  <?php
      $insertBuilder = Db::insert('users')
          ->set('login', 'example')
          ->set('email', 'example@domain.com');
      demo($insertBuilder->getQuery());
  ?>
</section>

<section class="mt-4">
  <h3>Update</h3>
  <hr/>
  <pre class="alert alert-secondary"><code>$updateBuilder = Db::update('users')
    ->setArray(
        [
            'status' => 'active',
            'updated' => date('Y-m-d H:i:s')
        ]
    )
    ->where('id = ?', 30);</code></pre>
  <?php
      $updateBuilder = Db::update('users')
          ->setArray(
              [
                  'status' => 'active',
                  'updated' => date('Y-m-d H:i:s')
              ]
          )
          ->where('id = ?', 30);
      demo($updateBuilder->getQuery());
  ?>
</section>

<section class="mt-4">
  <h3>Delete</h3>
  <hr/>
  <pre class="alert alert-secondary"><code>$deleteBuilder = Db::delete('users')
    ->where('id = ?', 5)
    ->limit(1);</code></pre>
  <?php
      $deleteBuilder = Db::delete('users')
          ->where('id = ?', 5)
          ->limit(1);
      demo($deleteBuilder->getQuery());
  ?>
</section>