<?php

use Application\Test;
use Application\Users;

require_once __DIR__ .'/partial/demo.phtml';
?>
<h2>Example of usage Db\Table methods</h2>
<p class="lead">Please, never use <code>DB</code> adapter inside <code>View</code></p>
<hr/>

<h3>Users Table</h3>
<hr/>
<pre class="alert alert-secondary"><code>Users\Table::getColumns()</code></pre>
<?php demo(Users\Table::getColumns()) ?>
<pre class="alert alert-secondary"><code>Users\Table::findRow(1)</code></pre>
<?php demo(Users\Table::findRow(1)) ?>
<pre class="alert alert-secondary"><code>Users\Table::findRowWhere(['id' => 2])</code></pre>
<?php demo(Users\Table::findRowWhere(['id' => 2])) ?>

<h3>Test Table</h3>
<hr/>
<?php $table = Test\Table::getInstance();?>
<pre class="alert alert-secondary"><code>$table = Test\Table::getInstance();
$table->saveTestRow();    <em>// <?=$table->saveTestRow()?></em>
$table->updateTestRows(); <em>// <?=$table->updateTestRows()?></em>
$table->deleteTestRows(); <em>// <?=$table->deleteTestRows()?></em></code></pre>
