<?php
use Application\Test;
use Bluz\Proxy\Db;

require_once __DIR__ .'/partial/demo.phtml';
?>

<h2>Example of usage DB package</h2>
<p class="lead">Please, never use <code>DB</code> adapter inside <code>View</code></p>
<hr/>
<?php
  $columns = Test\Table::getInstance()->getColumns();
  $records = Test\Table::select()->limit(10)->execute(PDO::FETCH_NUM);
  ?>
<h3>Table `test`</h3>
<table class="table">
  <thead>
    <tr>
      <?php foreach ($columns as $column): ?>
          <th><?=$column?></th>
      <?php endforeach; ?>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($records as $record) : ?>
      <tr>
        <?php foreach ($record as $column): ?>
          <td><?=$column?></td>
        <?php endforeach; ?>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<hr/>

<h3>Db::fetchOne</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchOne('SELECT count(*) FROM test LIMIT 1')</code></pre>
<?php demo(Db::fetchOne('SELECT count(*) FROM test LIMIT 1')) ?>

<h3>Db::fetchRow</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchRow('SELECT * FROM test WHERE name LIKE ?', ['a%'])</code></pre>
<?php demo(Db::fetchRow('SELECT * FROM test WHERE name LIKE ?', ['a%'])) ?>

<h3>Db::fetchAll</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchAll('SELECT * FROM test WHERE name LIKE ? ORDER BY name DESC LIMIT 10', ['a%'])</code></pre>
<?php demo(Db::fetchRow('SELECT * FROM test WHERE name LIKE ? ORDER BY name DESC LIMIT 10', ['a%'])) ?>

<h3>Db::fetchColumn</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchColumn('SELECT name FROM test WHERE name LIKE ? LIMIT 10', ['a%'])</code></pre>
<?php demo(Db::fetchColumn('SELECT name FROM test WHERE name LIKE ? LIMIT 10', ['a%'])) ?>

<h3>Db::fetchPairs</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchPairs('SELECT name, id FROM test LIMIT 10')</code></pre>
<?php demo(Db::fetchPairs('SELECT name, id FROM test LIMIT 10')) ?>

<h3>Db::fetchGroup</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchGroup('SELECT name, id FROM test LIMIT 10')</code></pre>
<?php demo(Db::fetchGroup('SELECT name, id FROM test LIMIT 10')) ?>

<h3>Db::fetchColumnGroup</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchColumnGroup('SELECT name, id FROM test LIMIT 10')</code></pre>
<?php demo(Db::fetchColumnGroup('SELECT name, id FROM test LIMIT 10')) ?>

<h3>Db::fetchColumnGroup</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchUniqueGroup('SELECT email, id, name FROM test LIMIT 10')</code></pre>
<?php demo(Db::fetchUniqueGroup('SELECT email, id, name FROM test LIMIT 10')) ?>

<h3>Db::fetchObject</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchObject('SELECT * FROM test LIMIT 1')</code></pre>
<?php demo(Db::fetchObject('SELECT * FROM test LIMIT 1')) ?>

<h3>Db::fetchObject</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchObject('SELECT * FROM test LIMIT 1', [], '\\Application\\Test\\Row')</code></pre>
<?php demo(Db::fetchObject('SELECT * FROM test LIMIT 1', [], '\\Application\\Test\\Row')) ?>

<h3>Db::fetchObject</h3>
<hr/>
<pre class="alert alert-secondary"><code>Db::fetchObject('SELECT * FROM test LIMIT 1', [], new Test\Row())</code></pre>
<?php demo(Db::fetchObject('SELECT * FROM test LIMIT 1', [], new Test\Row())) ?>
