<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
?>
<script type="module">
  // use data-spy="grid" for use AJAX for reload grid
  import '<?=$this->baseUrl('/js/bluz.grid.js');?>';
</script>

<div class="clearfix" data-spy="grid" data-grid="<?= $grid->getUid() ?>">
  <nav class="navbar navbar-light bg-light justify-content-start">
    <a class="navbar-brand" href="#">Filters:</a>
    <a href="<?= $grid->filter('id', 'gt', 3) ?>" class="btn btn-info ms-3" data-ajax>With Id &gt; 3</a>
    <a href="<?= $grid->filter('id', 'lt', 9) ?>" class="btn btn-info ms-3" data-ajax>With Id &lt; 9</a>
    <a href="<?= $grid->filter('id', 'ne', 5, false) ?>" class="btn btn-info ms-3" data-ajax>AND Id != 5</a>
  </nav>

  <hr/>

  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/limit.phtml', ['grid' => $grid]) ?>

  <table class="table grid">
    <thead>
      <tr>
        <th width="40px"><a href="<?= $grid->order('id', null, 'desc', false) ?>">Id</a></th>
        <th><a href="<?= $grid->order('name') ?>">Name</a></th>
        <th><a href="<?= $grid->order('email') ?>">Email</a></th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($grid->getData() as $row) : ?>
      <tr>
        <td><?= $row['id'] ?></td>
        <td><?= $row['name'] ?></td>
        <td><?= $row['email'] ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

  <?= $this->partial('grid/empty-rows.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
</div>
