<?php
$this->headScript($this->baseUrl('js/test/config.js'));

/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) {
    return;
}
?>
<script>
  // use data-spy="grid" for use AJAX for reload grid
  require(['bluz.grid']);
</script>

<div class="clearfix" data-spy="grid" data-grid="<?= $grid->getUid() ?>">
  <nav class="navbar navbar-light bg-light justify-content-start">
    <a class="navbar-brand ml-3" href="#">Filters:</a>
    <a href="<?= $grid->filter('status', 'eq', 'active') ?>" class="btn btn-info ml-3" data-ajax>All Active Users</a>
    <a href="<?= $grid->filter('id', 'gt', 30) ?>" class="btn btn-info ml-3" data-ajax>All users with Id &gt; 30</a>
    <a href="<?= $grid->filter('id', 'lt', 70, false) ?>" class="btn btn-info ml-3" data-ajax>AND users with Id &lt; 70</a>
    <a href="<?= $grid->filter('status', 'eq', 'active', false) ?>" class="btn btn-info ml-3" data-ajax>AND Active Users</a>
    <a href="<?= $grid->filter('id', 'ne', 42, false) ?>" class="btn btn-info ml-3" data-ajax>AND without user with Id = 42</a>
  </nav>
  <hr/>
  <nav class="navbar navbar-light bg-light justify-content-start">
    <a href="<?= $this->url('test', 'crud') ?>" class="btn btn-primary"
       data-ajax-dialog data-ajax-method="get">Create</a>
  </nav>

  <hr/>
  <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>
  <?= $this->partial('grid/limit.phtml', ['grid' => $grid]) ?>

  <table class="table grid">
    <thead>
    <tr>
      <th width="40px"><a href="<?= $grid->order('id') ?: '#' ?>">Id</a></th>
      <th><a href="<?= $grid->order('name') ?: '#' ?>">Name</a></th>
      <th><a href="<?= $grid->order('status') ?: '#' ?>">Status</a></th>
      <th width="120px"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($grid->getData() as $row) : ?>
      <tr>
        <td><?= $row['id'] ?></td>
        <td><?= $row['name'] ?></td>
        <td><?= $row['status'] ?></td>
        <td class="controls">
          <a href="<?= $this->url('test', 'crud', ['id' => $row['id']]) ?>" class="btn btn-primary"
             data-ajax-dialog data-ajax-method="get">
            <i class="fa fa-pencil"></i>
          </a>
          <a href="<?= $this->url('test', 'crud', ['id' => $row['id']]) ?>" class="btn btn-danger"
             data-confirm data-ajax data-ajax-method="delete">
            <i class="fa fa-times"></i>
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>

    <?= $this->partial('grid/empty-rows.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/pagination.phtml', ['grid' => $grid]) ?>
    <?= $this->partial('grid/total.phtml', ['grid' => $grid]) ?>

</div>
