<h2>Example of Mailer package</h2>
<hr/>
<p class="lead">Send &laquo;Hello!&raquo; e-mail message to:</p>

<form action="<?= $this->url('test', 'mailer') ?>" method="POST">
  <div class="form-group">
    <label class="input-group mb-1">
      <span class="input-group-text"><i class="bi bi-envelope"></i></span>
      <input type="email" class="form-control" name="email" value="<?= $email ?>" placeholder="<?= __('email') ?>"/>
    </label>
  </div>
  <button type="submit" class="btn btn-primary"><?= __('Send') ?></button>
</form>