<div class="modal-header">
    <h3 class="modal-title"><?=$title?></h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="<?= __('Close') ?>">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <?=$content?>
</div>
<div class="modal-footer">
    <a href="#" class="btn btn-light" data-dismiss="modal"><?= __('Close') ?></a>
</div>