<?php
use Bluz\Proxy\Request;

require_once __DIR__ .'/partial/demo.phtml';
?>

<h2>Example of usage Request package</h2>
<hr/>
<pre class="alert alert-secondary"><code>use Bluz\Proxy\Request;</code></pre>
<hr/>

<h3>Request::getMethod()</h3>
<hr/>
<?php demo(Request::getMethod()) ?>

<h3>Request::isCli()</h3>
<hr/>
<?php demo(Request::isCli() ? 'true' : 'false') ?>

<h3>Request::getUri()</h3>
<hr/>
<?php demo(Request::getUri()->__toString()) ?>

<h3>Request::getClientIp()</h3>
<hr/>
<?php demo(Request::getClientIp()) ?>
