<h2>Form View Helpers Examples</h2>
<hr/>
<form class="form-horizontal" method="post">
  <div class="form-group row">
    <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail" placeholder="Email">
    </div>
  </div>

  <div class="form-group">
    <label class="form-control-label">Sex</label>
    <div class="form-check">
      <label class="form-check-label">
          <?= $this->radio('sex', 'male', $sex, ['class' => 'form-check-input']) ?> Male
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label">
          <?= $this->radio('sex', 'female', $sex, ['class' => 'form-check-input']) ?> Female
      </label>
    </div>
    <div class="form-check disabled">
      <label class="form-check-label">
        <?= $this->radio('sex', 'none', $sex, ['class' => 'form-check-input', 'disabled' => 1]) ?> Not above
      </label>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="car">Car</label>
    <div class="col-sm-10 controls">
        <?=
        $this->select(
            'car',
            [
                'none' => 'No Car',
                'class-A' => [
                    'citroen-c1' => 'Citroen C1',
                    'mercedes-benz-a200' => 'Mercedes Benz A200',
                ],
                'class-B' => [
                    'audi-a1' => 'Audi A1',
                    'citroen-c3' => 'Citroen C3',
                ],
            ],
            $car,
            ['id' => 'car', 'class' => 'form-control']
        );
        ?>
    </div>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <?= $this->checkbox('remember', true, $remember, ['class' => 'form-check-input']) ?> Remember me
    </label>
  </div>
  <button type="submit" class="btn btn-primary col-sm-offset-2"><?= __('Send') ?></button>
</form>
<?php if (isset($params)) : ?>
  <h3>Request result</h3>
  <hr/>
    <?php var_dump($params) ?>
<?php endif; ?>